# Generated by Django 4.2.2 on 2023-06-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_delete_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('year', models.IntegerField()),
                ('seat_count', models.IntegerField()),
                ('body_type', models.CharField(max_length=25)),
                ('engine_volume', models.FloatField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
